import "./globals.css";
import { Roboto } from "next/font/google";
import CssBaseline from "@mui/material/CssBaseline";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "@/components/ReduxProvider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "eCommerceProd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <CssBaseline />
        <Toaster />

        <ReduxProvider>
          <div className="wrapper">
            <Header />
            {children}
            <Footer />
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
